/*
 * This file is part of the TrinityCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include "WorldSession.h"
#include "Bag.h"
#include "Common.h"
#include "DatabaseEnv.h"
#include "DBCStores.h"
#include "Opcodes.h"
#include "Item.h"
#include "Log.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "SpellInfo.h"
#include "QueryPackets.h"
#include "World.h"
#include "WorldPacket.h"

/**
 * @file ItemHandler.cpp
 * @brief 物品操作网络包处理模块
 *
 * @details 本文件实现了所有与物品相关的网络包处理函数。
 *          涵盖物品的查询、移动、装备、交易、销毁、附魔、镶嵌等操作。
 *
 * 主要功能模块：
 *
 * 1. 物品查询与信息获取
 *    - HandleItemQuerySingleOpcode(): 查询物品静态信息
 *    - HandleItemNameQueryOpcode(): 查询套装名称
 *    - HandleItemTextQuery(): 查询物品文本内容
 *
 * 2. 物品移动与交换
 *    - HandleSplitItemOpcode(): 分割物品堆叠
 *    - HandleSwapInvItemOpcode(): 背包内交换物品
 *    - HandleSwapItem(): 通用物品交换
 *    - HandleAutoStoreBagItemOpcode(): 自动存储到背包
 *
 * 3. 物品装备与卸下
 *    - HandleAutoEquipItemOpcode(): 自动装备物品
 *    - HandleAutoEquipItemSlotOpcode(): 装备到指定槽位
 *    - HandleCancelTempEnchantmentOpcode(): 取消临时附魔
 *
 * 4. 商人交互
 *    - HandleListInventoryOpcode(): 列出商人库存
 *    - HandleBuyItemOpcode(): 购买物品
 *    - HandleBuyItemInSlotOpcode(): 购买到指定槽位
 *    - HandleSellItemOpcode(): 出售物品
 *    - HandleBuybackItem(): 购回物品
 *
 * 5. 物品修改与附魔
 *    - HandleSocketOpcode(): 镶嵌宝石
 *    - HandleWrapItemOpcode(): 包装物品
 *    - SendEnchantmentLog(): 发送附魔日志
 *    - SendItemEnchantTimeUpdate(): 更新附魔时间
 *
 * 6. 其他功能
 *    - HandleDestroyItemOpcode(): 销毁物品
 *    - HandleReadItem(): 阅读物品
 *    - HandleSetAmmoOpcode(): 设置弹药
 *    - HandleItemRefundInfoRequest(): 请求退款信息
 *    - HandleItemRefund(): 执行物品退款
 *
 * @note 所有处理函数都是 WorldSession 类的成员函数
 * @note 网络包数据通过 WorldPacket 类传递
 */

/**
 * @brief 处理分割物品网络包（CMSG_SPLIT_ITEM）
 *
 * @details 当玩家想要将一堆物品分成两部分时调用此函数。
 *          例如：将20个物品中的一半（10个）移动到另一个空槽位。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - srcbag: 源背包编号
 *        - srcslot: 源槽位编号
 *        - dstbag: 目标背包编号
 *        - dstslot: 目标槽位编号
 *        - count: 要分割的物品数量
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取源和目标位置信息
 *       2. 验证源位置和目标位置的有效性
 *       3. 调用 Player::SplitItem() 执行实际的分割操作
 */
void WorldSession::HandleSplitItemOpcode(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_SPLIT_ITEM");
    uint8 srcbag, srcslot, dstbag, dstslot;
    uint32 count;

    recvData >> srcbag >> srcslot >> dstbag >> dstslot >> count;
    //TC_LOG_DEBUG("STORAGE: receive srcbag = {}, srcslot = {}, dstbag = {}, dstslot = {}, count = {}", srcbag, srcslot, dstbag, dstslot, count);

    uint16 src = ((srcbag << 8) | srcslot);
    uint16 dst = ((dstbag << 8) | dstslot);

    if (src == dst)
        return;

    if (count == 0)
        return;                                             //check count - if zero it's fake packet

    if (!_player->IsValidPos(srcbag, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
        return;
    }

    if (!_player->IsValidPos(dstbag, dstslot, false))       // can be autostore pos
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, nullptr, nullptr);
        return;
    }

    _player->SplitItem(src, dst, count);
}

/**
 * @brief 处理背包内交换物品网络包（CMSG_SWAP_INV_ITEM）
 *
 * @details 当玩家在主背包（背包0）内交换两个槽位的物品时调用此函数。
 *          注意：此函数仅处理主背包内的交换，不涉及其他背包。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - dstslot: 目标槽位编号
 *        - srcslot: 源槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取源和目标槽位
 *       2. 验证源槽位和目标槽位的有效性
 *       3. 检查银行访问权限（如果涉及银行槽位）
 *       4. 调用 Player::SwapItem() 执行交换操作
 */
void WorldSession::HandleSwapInvItemOpcode(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_SWAP_INV_ITEM");
    uint8 srcslot, dstslot;

    recvData >> dstslot >> srcslot;
    //TC_LOG_DEBUG("STORAGE: receive srcslot = {}, dstslot = {}", srcslot, dstslot);

    // prevent attempt swap same item to current position generated by client at special checting sequence
    if (srcslot == dstslot)
        return;

    if (!_player->IsValidPos(INVENTORY_SLOT_BAG_0, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
        return;
    }

    if (!_player->IsValidPos(INVENTORY_SLOT_BAG_0, dstslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, nullptr, nullptr);
        return;
    }

    if (_player->IsBankPos(INVENTORY_SLOT_BAG_0, srcslot) && !CanUseBank())
    {
        TC_LOG_DEBUG("network", "WORLD: HandleSwapInvItemOpcode - Unit ({}) not found or you can't interact with him.", m_currentBankerGUID.ToString());
        return;
    }

    if (_player->IsBankPos(INVENTORY_SLOT_BAG_0, dstslot) && !CanUseBank())
    {
        TC_LOG_DEBUG("network", "WORLD: HandleSwapInvItemOpcode - Unit ({}) not found or you can't interact with him.", m_currentBankerGUID.ToString());
        return;
    }

    uint16 src = ((INVENTORY_SLOT_BAG_0 << 8) | srcslot);
    uint16 dst = ((INVENTORY_SLOT_BAG_0 << 8) | dstslot);

    _player->SwapItem(src, dst);
}

/**
 * @brief 处理自动装备物品到指定槽位网络包（CMSG_AUTOEQUIP_ITEM_SLOT）
 *
 * @details 当玩家右键点击背包中的可装备物品，指定装备到某个特定槽位时调用此函数。
 *          客户端会自动选择合适的装备槽位，然后将物品装备上去。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - itemguid: 物品的唯一标识符（GUID）
 *        - dstslot: 目标装备槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品GUID和目标槽位
 *       2. 验证目标槽位是否为装备槽位（防止作弊）
 *       3. 获取物品对象并验证其存在性
 *       4. 调用 Player::SwapItem() 将物品装备到目标槽位
 */
void WorldSession::HandleAutoEquipItemSlotOpcode(WorldPacket& recvData)
{
    ObjectGuid itemguid;
    uint8 dstslot;
    recvData >> itemguid >> dstslot;

    // cheating attempt, client should never send opcode in that case
    if (!Player::IsEquipmentPos(INVENTORY_SLOT_BAG_0, dstslot))
        return;

    Item* item = _player->GetItemByGuid(itemguid);
    uint16 dstpos = dstslot | (INVENTORY_SLOT_BAG_0 << 8);

    if (!item || item->GetPos() == dstpos)
        return;

    _player->SwapItem(item->GetPos(), dstpos);
}

/**
 * @brief 处理交换物品网络包（CMSG_SWAP_ITEM）
 *
 * @details 当玩家拖拽物品从一个位置移动到另一个位置时调用此函数。
 *          这是最通用的物品交换函数，支持跨背包操作。
 *          如果目标位置已有物品，则两个物品会互换位置。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - dstbag: 目标背包编号
 *        - dstslot: 目标槽位编号
 *        - srcbag: 源背包编号
 *        - srcslot: 源槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取源和目标位置信息
 *       2. 验证源位置和目标位置的有效性
 *       3. 检查银行访问权限（如果涉及银行位置）
 *       4. 调用 Player::SwapItem() 执行交换操作
 */
void WorldSession::HandleSwapItem(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_SWAP_ITEM");
    uint8 dstbag, dstslot, srcbag, srcslot;

    recvData >> dstbag >> dstslot >> srcbag >> srcslot;
    //TC_LOG_DEBUG("STORAGE: receive srcbag = {}, srcslot = {}, dstbag = {}, dstslot = {}", srcbag, srcslot, dstbag, dstslot);

    uint16 src = ((srcbag << 8) | srcslot);
    uint16 dst = ((dstbag << 8) | dstslot);

    // prevent attempt swap same item to current position generated by client at special checting sequence
    if (src == dst)
        return;

    if (!_player->IsValidPos(srcbag, srcslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
        return;
    }

    if (!_player->IsValidPos(dstbag, dstslot, true))
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, nullptr, nullptr);
        return;
    }

    if (_player->IsBankPos(srcbag, srcslot) && !CanUseBank())
    {
        TC_LOG_DEBUG("network", "WORLD: HandleSwapItem - Unit ({}) not found or you can't interact with him.", m_currentBankerGUID.ToString());
        return;
    }

    if (_player->IsBankPos(dstbag, dstslot) && !CanUseBank())
    {
        TC_LOG_DEBUG("network", "WORLD: HandleSwapItem - Unit ({}) not found or you can't interact with him.", m_currentBankerGUID.ToString());
        return;
    }

    _player->SwapItem(src, dst);
}

/**
 * @brief 处理自动装备物品网络包（CMSG_AUTOEQUIP_ITEM）
 *
 * @details 当玩家右键点击背包中的可装备物品时调用此函数。
 *          系统会自动找到合适的装备槽位并将物品装备上去。
 *          如果目标槽位已有装备，则会尝试将原装备移动到源位置。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - srcbag: 源背包编号
 *        - srcslot: 源槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取源位置信息
 *       2. 获取源物品并验证其存在性
 *       3. 检查物品是否可以被装备
 *       4. 如果目标槽位为空，直接装备物品
 *       5. 如果目标槽位已有物品，执行交换操作：
 *          - 验证目标物品是否可以卸下
 *          - 检查目标物品是否可以放入源位置
 *          - 执行交换操作
 *       6. 处理副手武器自动卸下逻辑
 *       7. 更新物品依赖的光环效果
 */
void WorldSession::HandleAutoEquipItemOpcode(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_AUTOEQUIP_ITEM");
    uint8 srcbag, srcslot;

    recvData >> srcbag >> srcslot;
    //TC_LOG_DEBUG("STORAGE: receive srcbag = {}, srcslot = {}", srcbag, srcslot);

    Item* pSrcItem  = _player->GetItemByPos(srcbag, srcslot);
    if (!pSrcItem)
        return;                                             // only at cheat

    uint16 dest;
    InventoryResult msg = _player->CanEquipItem(NULL_SLOT, dest, pSrcItem, !pSrcItem->IsBag());
    if (msg != EQUIP_ERR_OK)
    {
        _player->SendEquipError(msg, pSrcItem, nullptr);
        return;
    }

    uint16 src = pSrcItem->GetPos();
    if (dest == src)                                           // prevent equip in same slot, only at cheat
        return;

    Item* pDstItem = _player->GetItemByPos(dest);
    if (!pDstItem)                                         // empty slot, simple case
    {
        _player->RemoveItem(srcbag, srcslot, true);
        _player->EquipItem(dest, pSrcItem, true);
        _player->AutoUnequipOffhandIfNeed();
    }
    else                                                    // have currently equipped item, not simple case
    {
        uint8 dstbag = pDstItem->GetBagSlot();
        uint8 dstslot = pDstItem->GetSlot();

        msg = _player->CanUnequipItem(dest, !pSrcItem->IsBag());
        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, pDstItem, nullptr);
            return;
        }

        // check dest->src move possibility
        ItemPosCountVec sSrc;
        uint16 eSrc = 0;
        if (_player->IsInventoryPos(src))
        {
            msg = _player->CanStoreItem(srcbag, srcslot, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
                msg = _player->CanStoreItem(srcbag, NULL_SLOT, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
                msg = _player->CanStoreItem(NULL_BAG, NULL_SLOT, sSrc, pDstItem, true);
        }
        else if (_player->IsBankPos(src))
        {
            msg = _player->CanBankItem(srcbag, srcslot, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
                msg = _player->CanBankItem(srcbag, NULL_SLOT, sSrc, pDstItem, true);
            if (msg != EQUIP_ERR_OK)
                msg = _player->CanBankItem(NULL_BAG, NULL_SLOT, sSrc, pDstItem, true);
        }
        else if (_player->IsEquipmentPos(src))
        {
            msg = _player->CanEquipItem(srcslot, eSrc, pDstItem, true);
            if (msg == EQUIP_ERR_OK)
                msg = _player->CanUnequipItem(eSrc, true);
        }

        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, pDstItem, pSrcItem);
            return;
        }

        // now do moves, remove...
        _player->RemoveItem(dstbag, dstslot, false);
        _player->RemoveItem(srcbag, srcslot, false);

        // add to dest
        _player->EquipItem(dest, pSrcItem, true);

        // add to src
        if (_player->IsInventoryPos(src))
            _player->StoreItem(sSrc, pDstItem, true);
        else if (_player->IsBankPos(src))
            _player->BankItem(sSrc, pDstItem, true);
        else if (_player->IsEquipmentPos(src))
            _player->EquipItem(eSrc, pDstItem, true);

        _player->AutoUnequipOffhandIfNeed();

        // if inventory item was moved, check if we can remove dependent auras, because they were not removed in Player::RemoveItem (update was set to false)
        // do this after swaps are done, we pass nullptr because both weapons could be swapped and none of them should be ignored
        if ((srcbag == INVENTORY_SLOT_BAG_0 && srcslot < INVENTORY_SLOT_BAG_END) || (dstbag == INVENTORY_SLOT_BAG_0 && dstslot < INVENTORY_SLOT_BAG_END))
            _player->ApplyItemDependentAuras((Item*)nullptr, false);
    }
}

/**
 * @brief 处理销毁物品网络包（CMSG_DESTROYITEM）
 *
 * @details 当玩家主动删除物品时调用此函数。
 *          玩家可以通过右键点击物品选择删除，或拖拽物品到空白区域删除。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - bag: 物品所在背包编号
 *        - slot: 物品所在槽位编号
 *        - count: 要销毁的数量（如果为0则销毁整组）
 *        - data1/data2/data3: 未使用的附加数据
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品位置和数量
 *       2. 检查装备槽位和背包槽位的卸下权限
 *       3. 验证物品是否存在
 *       4. 检查物品是否允许玩家销毁（某些特殊物品不可销毁）
 *       5. 根据数量决定销毁部分或全部物品
 */
void WorldSession::HandleDestroyItemOpcode(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_DESTROYITEM");
    uint8 bag, slot, count, data1, data2, data3;

    recvData >> bag >> slot >> count >> data1 >> data2 >> data3;
    //TC_LOG_DEBUG("STORAGE: receive bag = {}, slot = {}, count = {}", bag, slot, count);

    uint16 pos = (bag << 8) | slot;

    // prevent drop unequipable items (in combat, for example) and non-empty bags
    if (_player->IsEquipmentPos(pos) || _player->IsBagPos(pos))
    {
        InventoryResult msg = _player->CanUnequipItem(pos, false);
        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, _player->GetItemByPos(pos), nullptr);
            return;
        }
    }

    Item* pItem  = _player->GetItemByPos(bag, slot);
    if (!pItem)
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
        return;
    }

    if (pItem->GetTemplate()->HasFlag(ITEM_FLAG_NO_USER_DESTROY))
    {
        _player->SendEquipError(EQUIP_ERR_CANT_DROP_SOULBOUND, nullptr, nullptr);
        return;
    }

    if (count)
    {
        uint32 i_count = count;
        _player->DestroyItemCount(pItem, i_count, true);
    }
    else
        _player->DestroyItem(bag, slot, true);
}

/**
 * @brief 处理查询单个物品信息网络包（CMSG_ITEM_QUERY_SINGLE）
 *
 * @details 当客户端需要获取某个物品的详细信息时调用此函数。
 *          例如：玩家查看物品提示信息、拍卖行浏览物品等场景。
 *          此函数返回物品的静态数据（名称、描述、属性等）。
 *
 * @param query 查询包数据，包含以下字段：
 *        - ItemID: 要查询的物品模板ID（Entry）
 *
 * @return 无返回值（通过发送响应包返回数据）
 *
 * @note 主要流程：
 *       1. 根据物品ID查找物品模板
 *       2. 如果找到模板：
 *          - 如果启用了数据缓存，发送预构建的查询数据
 *          - 否则构建并发送查询响应数据
 *       3. 如果未找到模板，发送空响应包
 *
 * @note 只发送静态数据，不包含物品实例的动态数据（如附魔、耐久度等）
 */
// Only _static_ data send in this packet !!!
void WorldSession::HandleItemQuerySingleOpcode(WorldPackets::Query::QueryItemSingle& query)
{
    TC_LOG_INFO("network", "STORAGE: Item Query = {}", query.ItemID);

    if (ItemTemplate const* itemTemplate = sObjectMgr->GetItemTemplate(query.ItemID))
    {
        if (sWorld->getBoolConfig(CONFIG_CACHE_DATA_QUERIES))
            SendPacket(&itemTemplate->QueryData[static_cast<uint32>(GetSessionDbLocaleIndex())]);
        else
        {
            WorldPacket response = itemTemplate->BuildQueryData(GetSessionDbLocaleIndex());
            SendPacket(&response);
        }
    }
    else
    {
        TC_LOG_DEBUG("network", "WORLD: CMSG_ITEM_QUERY_SINGLE - NO item INFO! (ENTRY: {})", query.ItemID);
        WorldPackets::Query::QueryItemSingleResponse response;
        response.ItemID = query.ItemID;
        SendPacket(response.Write());
    }
}

/**
 * @brief 处理阅读物品网络包（CMSG_READ_ITEM）
 *
 * @details 当玩家尝试阅读包含页面文本的物品时调用此函数。
 *          例如：书籍、信件、任务文档等可阅读物品。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - bag: 物品所在背包编号
 *        - slot: 物品所在槽位编号
 *
 * @return 无返回值（通过发送响应包返回结果）
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品位置
 *       2. 获取物品对象并验证其存在性
 *       3. 检查物品是否包含页面文本
 *       4. 验证玩家是否可以使用该物品
 *       5. 发送阅读成功或失败的响应包
 */
void WorldSession::HandleReadItem(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_READ_ITEM");

    uint8 bag, slot;
    recvData >> bag >> slot;

    //TC_LOG_INFO("network", "STORAGE: Read bag = {}, slot = {}", bag, slot);
    Item* pItem = _player->GetItemByPos(bag, slot);

    if (pItem && pItem->GetTemplate()->PageText)
    {
        WorldPacket data;

        InventoryResult msg = _player->CanUseItem(pItem);
        if (msg == EQUIP_ERR_OK)
        {
            data.Initialize (SMSG_READ_ITEM_OK, 8);
            TC_LOG_INFO("network", "STORAGE: Item page sent");
        }
        else
        {
            data.Initialize(SMSG_READ_ITEM_FAILED, 8);
            TC_LOG_INFO("network", "STORAGE: Unable to read item");
            _player->SendEquipError(msg, pItem, nullptr);
        }
        data << pItem->GetGUID();
        SendPacket(&data);
    }
    else
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
}

/**
 * @brief 处理出售物品给商人网络包（CMSG_SELL_ITEM）
 *
 * @details 当玩家向商人出售物品时调用此函数。
 *          玩家可以通过拖拽物品到商人窗口或右键点击物品出售。
 *          出售的物品会进入回购列表，玩家可以在一定时间内购回。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - vendorguid: 商人的唯一标识符（GUID）
 *        - itemguid: 物品的唯一标识符（GUID）
 *        - count: 要出售的数量（0表示出售全部）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 验证商人是否存在且可交互
 *       2. 验证物品是否存在且属于玩家
 *       3. 检查物品是否可以出售（非空背包、非正在拾取、非可退款）
 *       4. 计算出售价格（考虑声望折扣）
 *       5. 如果出售部分数量，克隆物品并更新原物品数量
 *       6. 如果出售全部，移动物品到回购槽位
 *       7. 增加玩家金币并更新成就进度
 */
void WorldSession::HandleSellItemOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: Received CMSG_SELL_ITEM");
    ObjectGuid vendorguid, itemguid;
    uint32 count;

    recvData >> vendorguid >> itemguid >> count;

    if (!itemguid)
        return;

    Creature* creature = GetPlayer()->GetNPCIfCanInteractWith(vendorguid, UNIT_NPC_FLAG_VENDOR);
    if (!creature)
    {
        TC_LOG_DEBUG("network", "WORLD: HandleSellItemOpcode - {} not found or you can not interact with him.", vendorguid.ToString());
        _player->SendSellError(SELL_ERR_CANT_FIND_VENDOR, nullptr, itemguid, 0);
        return;
    }

    if ((creature->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_NO_SELL_VENDOR) != 0)
    {
        _player->SendSellError(SELL_ERR_CANT_SELL_TO_THIS_MERCHANT, creature, itemguid, 0);
        return;
    }

    // remove fake death
    if (GetPlayer()->HasUnitState(UNIT_STATE_DIED))
        GetPlayer()->RemoveAurasByType(SPELL_AURA_FEIGN_DEATH);

    Item* pItem = _player->GetItemByGuid(itemguid);
    if (pItem)
    {
        // prevent sell not owner item
        if (_player->GetGUID() != pItem->GetOwnerGUID())
        {
            _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
            return;
        }

        // prevent sell non empty bag by drag-and-drop at vendor's item list
        if (pItem->IsNotEmptyBag())
        {
            _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
            return;
        }

        // prevent sell currently looted item
        if (_player->GetLootGUID() == pItem->GetGUID())
        {
            _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
            return;
        }

        // prevent selling item for sellprice when the item is still refundable
        // this probably happens when right clicking a refundable item, the client sends both
        // CMSG_SELL_ITEM and CMSG_REFUND_ITEM (unverified)
        if (pItem->IsRefundable())
            return; // Therefore, no feedback to client

        // special case at auto sell (sell all)
        if (count == 0)
            count = pItem->GetCount();
        else
        {
            // prevent sell more items that exist in stack (possible only not from client)
            if (count > pItem->GetCount())
            {
                _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
                return;
            }
        }

        ItemTemplate const* pProto = pItem->GetTemplate();
        if (pProto)
        {
            if (pProto->SellPrice > 0)
            {
                uint32 money = pProto->SellPrice * count;
                if (_player->GetMoney() >= MAX_MONEY_AMOUNT - money)               // prevent exceeding gold limit
                {
                    _player->SendEquipError(EQUIP_ERR_TOO_MUCH_GOLD, nullptr, nullptr);
                    _player->SendSellError(SELL_ERR_UNK, creature, itemguid, 0);
                    return;
                }

                if (count < pItem->GetCount())               // need split items
                {
                    Item* pNewItem = pItem->CloneItem(count, _player);
                    if (!pNewItem)
                    {
                        TC_LOG_ERROR("network", "WORLD: HandleSellItemOpcode - could not create clone of item {}; count = {}", pItem->GetEntry(), count);
                        _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
                        return;
                    }

                    pItem->SetCount(pItem->GetCount() - count);
                    _player->ItemRemovedQuestCheck(pItem->GetEntry(), count);
                    if (_player->IsInWorld())
                        pItem->SendUpdateToPlayer(_player);
                    pItem->SetState(ITEM_CHANGED, _player);

                    _player->AddItemToBuyBackSlot(pNewItem);
                    if (_player->IsInWorld())
                        pNewItem->SendUpdateToPlayer(_player);
                }
                else
                {
                    _player->RemoveItem(pItem->GetBagSlot(), pItem->GetSlot(), true);
                    _player->ItemRemovedQuestCheck(pItem->GetEntry(), pItem->GetCount());
                    RemoveItemFromUpdateQueueOf(pItem, _player);
                    _player->AddItemToBuyBackSlot(pItem);
                }

                _player->ModifyMoney(money);
                _player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, money);
            }
            else
                _player->SendSellError(SELL_ERR_CANT_SELL_ITEM, creature, itemguid, 0);
            return;
        }
    }
    _player->SendSellError(SELL_ERR_CANT_FIND_ITEM, creature, itemguid, 0);
    return;
}

/**
 * @brief 处理购回物品网络包（CMSG_BUYBACK_ITEM）
 *
 * @details 当玩家想要从商人处购回之前出售的物品时调用此函数。
 *          玩家可以在一定时间内以原出售价格购回物品。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - vendorguid: 商人的唯一标识符（GUID）
 *        - slot: 回购槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 验证商人是否存在且可交互
 *       2. 从回购槽位获取物品
 *       3. 检查玩家是否有足够的金币
 *       4. 检查玩家背包是否有空间
 *       5. 扣除金币并将物品放入玩家背包
 */
void WorldSession::HandleBuybackItem(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: Received CMSG_BUYBACK_ITEM");
    ObjectGuid vendorguid;
    uint32 slot;

    recvData >> vendorguid >> slot;

    Creature* creature = GetPlayer()->GetNPCIfCanInteractWith(vendorguid, UNIT_NPC_FLAG_VENDOR);
    if (!creature)
    {
        TC_LOG_DEBUG("network", "WORLD: HandleBuybackItem - Unit ({}) not found or you can not interact with him.", vendorguid.ToString());
        _player->SendSellError(SELL_ERR_CANT_FIND_VENDOR, nullptr, ObjectGuid::Empty, 0);
        return;
    }

    // remove fake death
    if (GetPlayer()->HasUnitState(UNIT_STATE_DIED))
        GetPlayer()->RemoveAurasByType(SPELL_AURA_FEIGN_DEATH);

    Item* pItem = _player->GetItemFromBuyBackSlot(slot);
    if (pItem)
    {
        uint32 price = _player->GetUInt32Value(PLAYER_FIELD_BUYBACK_PRICE_1 + slot - BUYBACK_SLOT_START);
        if (!_player->HasEnoughMoney(price))
        {
            _player->SendBuyError(BUY_ERR_NOT_ENOUGHT_MONEY, creature, pItem->GetEntry(), 0);
            return;
        }

        ItemPosCountVec dest;
        InventoryResult msg = _player->CanStoreItem(NULL_BAG, NULL_SLOT, dest, pItem, false);
        if (msg == EQUIP_ERR_OK)
        {
            _player->ModifyMoney(-(int32)price);
            _player->RemoveItemFromBuyBackSlot(slot, false);
            _player->ItemAddedQuestCheck(pItem->GetEntry(), pItem->GetCount());
            _player->StoreItem(dest, pItem, true);
        }
        else
            _player->SendEquipError(msg, pItem, nullptr);
        return;
    }
    else
        _player->SendBuyError(BUY_ERR_CANT_FIND_ITEM, creature, 0, 0);
}

/**
 * @brief 处理购买物品到指定槽位网络包（CMSG_BUY_ITEM_IN_SLOT）
 *
 * @details 当玩家从商人处购买物品并指定放入特定背包槽位时调用此函数。
 *          允许玩家精确控制购买物品的存放位置。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - vendorguid: 商人的唯一标识符（GUID）
 *        - item: 物品模板ID
 *        - slot: 商人出售列表中的槽位（客户端发送的值+1）
 *        - bagguid: 目标背包的唯一标识符（GUID）
 *        - bagslot: 目标背包中的槽位编号
 *        - count: 购买数量
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包数据
 *       2. 调整商人槽位索引（客户端从1开始计数）
 *       3. 根据背包GUID查找对应的背包槽位
 *       4. 调用 Player::BuyItemFromVendorSlot() 执行购买操作
 */
void WorldSession::HandleBuyItemInSlotOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: Received CMSG_BUY_ITEM_IN_SLOT");
    ObjectGuid vendorguid, bagguid;
    uint32 item, slot, count;
    uint8 bagslot;

    recvData >> vendorguid >> item  >> slot >> bagguid >> bagslot >> count;

    // client expects count starting at 1, and we send vendorslot+1 to client already
    if (slot > 0)
        --slot;
    else
        return;                                             // cheating

    uint8 bag = NULL_BAG;                                   // init for case invalid bagGUID

    // find bag slot by bag guid
    if (bagguid == _player->GetGUID())
        bag = INVENTORY_SLOT_BAG_0;
    else
    {
        for (int i = INVENTORY_SLOT_BAG_START; i < INVENTORY_SLOT_BAG_END; ++i)
        {
            if (Bag* pBag = _player->GetBagByPos(i))
            {
                if (bagguid == pBag->GetGUID())
                {
                    bag = i;
                    break;
                }
            }
        }
    }

    // bag not found, cheating?
    if (bag == NULL_BAG)
        return;

    GetPlayer()->BuyItemFromVendorSlot(vendorguid, slot, item, count, bag, bagslot);
}

/**
 * @brief 处理购买物品网络包（CMSG_BUY_ITEM）
 *
 * @details 当玩家从商人处购买物品时调用此函数。
 *          系统会自动找到合适的背包位置存放购买的物品。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - vendorguid: 商人的唯一标识符（GUID）
 *        - item: 物品模板ID
 *        - slot: 商人出售列表中的槽位（客户端发送的值+1）
 *        - count: 购买数量
 *        - unk1: 未使用的附加数据
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包数据
 *       2. 调整商人槽位索引（客户端从1开始计数）
 *       3. 调用 Player::BuyItemFromVendorSlot() 执行购买操作
 */
void WorldSession::HandleBuyItemOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: Received CMSG_BUY_ITEM");
    ObjectGuid vendorguid;
    uint32 item, slot, count;
    uint8 unk1;

    recvData >> vendorguid >> item >> slot >> count >> unk1;

    // client expects count starting at 1, and we send vendorslot+1 to client already
    if (slot > 0)
        --slot;
    else
        return; // cheating

    GetPlayer()->BuyItemFromVendorSlot(vendorguid, slot, item, count, NULL_BAG, NULL_SLOT);
}

/**
 * @brief 处理列出商人库存网络包（CMSG_LIST_INVENTORY）
 *
 * @details 当玩家打开商人界面时调用此函数。
 *          请求商人出售的物品列表。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - guid: 商人的唯一标识符（GUID）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取商人GUID
 *       2. 验证玩家是否存活
 *       3. 调用 SendListInventory() 发送商人物品列表
 */
void WorldSession::HandleListInventoryOpcode(WorldPacket& recvData)
{
    ObjectGuid guid;

    recvData >> guid;

    if (!GetPlayer()->IsAlive())
        return;

    TC_LOG_DEBUG("network", "WORLD: Recvd CMSG_LIST_INVENTORY");

    SendListInventory(guid);
}

/**
 * @brief 发送商人库存列表给客户端
 *
 * @details 构建并发送商人出售物品列表的网络包。
 *          包含物品ID、显示信息、库存数量、价格、耐久度、购买数量、扩展成本等信息。
 *          会根据玩家的职业、阵营、声望等进行过滤和折扣计算。
 *
 * @param vendorGuid 商人的唯一标识符（GUID）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 验证商人是否存在且可交互
 *       2. 暂停商人的移动
 *       3. 获取商人的出售物品列表
 *       4. 遍历所有物品，过滤不符合条件的物品：
 *          - 职业限制（拾取绑定的物品）
 *          - 阵营限制（联盟/部落专属物品）
 *          - 库存限制（已售罄的物品）
 *          - 条件限制（条件不满足的物品）
 *       5. 计算声望折扣后的价格
 *       6. 构建并发送物品列表数据包
 */
void WorldSession::SendListInventory(ObjectGuid vendorGuid)
{
    Creature* vendor = GetPlayer()->GetNPCIfCanInteractWith(vendorGuid, UNIT_NPC_FLAG_VENDOR);
    if (!vendor)
    {
        TC_LOG_DEBUG("network", "WORLD: SendListInventory - {} not found or you can not interact with him.", vendorGuid.ToString());
        _player->SendSellError(SELL_ERR_CANT_FIND_VENDOR, nullptr, ObjectGuid::Empty, 0);
        return;
    }

    // remove fake death
    if (GetPlayer()->HasUnitState(UNIT_STATE_DIED))
        GetPlayer()->RemoveAurasByType(SPELL_AURA_FEIGN_DEATH);

    // Stop the npc if moving
    if (uint32 pause = vendor->GetMovementTemplate().GetInteractionPauseTimer())
        vendor->PauseMovement(pause);
    vendor->SetHomePosition(vendor->GetPosition());

    VendorItemData const* items = vendor->GetVendorItems();
    if (!items)
    {
        WorldPacket data(SMSG_LIST_INVENTORY, 8 + 1 + 1);
        data << uint64(vendorGuid);
        data << uint8(0);                                   // count == 0, next will be error code
        data << uint8(0);                                   // "Vendor has no inventory"
        SendPacket(&data);
        return;
    }

    uint8 itemCount = items->GetItemCount();
    uint8 count = 0;

    WorldPacket data(SMSG_LIST_INVENTORY, 8 + 1 + itemCount * 8 * 4);
    data << uint64(vendorGuid);

    size_t countPos = data.wpos();
    data << uint8(count);

    float discountMod = _player->GetReputationPriceDiscount(vendor);

    for (uint8 slot = 0; slot < itemCount; ++slot)
    {
        if (VendorItem const* item = items->GetItem(slot))
        {
            if (ItemTemplate const* itemTemplate = sObjectMgr->GetItemTemplate(item->item))
            {
                if (!(itemTemplate->AllowableClass & _player->GetClassMask()) && itemTemplate->Bonding == BIND_WHEN_PICKED_UP && !_player->IsGameMaster())
                    continue;
                // Only display items in vendor lists for the team the
                // player is on. If GM on, display all items.
                if (!_player->IsGameMaster() && ((itemTemplate->HasFlag(ITEM_FLAG2_FACTION_HORDE) && _player->GetTeam() == ALLIANCE) || (itemTemplate->HasFlag(ITEM_FLAG2_FACTION_ALLIANCE) && _player->GetTeam() == HORDE)))
                    continue;

                // Items sold out are not displayed in list
                uint32 leftInStock = !item->maxcount ? 0xFFFFFFFF : vendor->GetVendorItemCurrentCount(item);
                if (!_player->IsGameMaster() && !leftInStock)
                    continue;

                if (!sConditionMgr->IsObjectMeetingVendorItemConditions(vendor->GetEntry(), item->item, _player, vendor))
                {
                    TC_LOG_DEBUG("condition", "SendListInventory: conditions not met for creature entry {} item {}", vendor->GetEntry(), item->item);
                    continue;
                }

                // reputation discount
                int32 price = item->IsGoldRequired(itemTemplate) ? uint32(floor(itemTemplate->BuyPrice * discountMod)) : 0;

                data << uint32(slot + 1);       // client expects counting to start at 1
                data << uint32(item->item);
                data << uint32(itemTemplate->DisplayInfoID);
                data << int32(leftInStock);
                data << uint32(price);
                data << uint32(itemTemplate->MaxDurability);
                data << uint32(itemTemplate->BuyCount);
                data << uint32(item->ExtendedCost);

                if (++count >= MAX_VENDOR_ITEMS)
                    break;
            }
        }
    }

    if (count == 0)
    {
        data << uint8(0);
        SendPacket(&data);
        return;
    }

    data.put<uint8>(countPos, count);
    SendPacket(&data);
}

/**
 * @brief 处理自动存储背包物品网络包（CMSG_AUTOSTORE_BAG_ITEM）
 *
 * @details 当玩家想要将物品移动到指定背包的任意可用槽位时调用此函数。
 *          系统会自动找到背包中第一个可用的槽位存放物品。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - srcbag: 源背包编号
 *        - srcslot: 源槽位编号
 *        - dstbag: 目标背包编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取源位置和目标背包
 *       2. 获取源物品并验证其存在性
 *       3. 验证目标背包位置的有效性
 *       4. 如果是装备槽位或背包槽位，检查卸下权限
 *       5. 检查物品是否可以存储到目标背包
 *       6. 如果目标位置就是当前位置，发送成功消息
 *       7. 否则执行移动物品操作
 */
void WorldSession::HandleAutoStoreBagItemOpcode(WorldPacket& recvData)
{
    //TC_LOG_DEBUG("network", "WORLD: CMSG_AUTOSTORE_BAG_ITEM");
    uint8 srcbag, srcslot, dstbag;

    recvData >> srcbag >> srcslot >> dstbag;
    //TC_LOG_DEBUG("STORAGE: receive srcbag = {}, srcslot = {}, dstbag = {}", srcbag, srcslot, dstbag);

    Item* pItem = _player->GetItemByPos(srcbag, srcslot);
    if (!pItem)
        return;

    if (!_player->IsValidPos(dstbag, NULL_SLOT, false))      // can be autostore pos
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, nullptr, nullptr);
        return;
    }

    uint16 src = pItem->GetPos();

    // check unequip potability for equipped items and bank bags
    if (_player->IsEquipmentPos (src) || _player->IsBagPos (src))
    {
        InventoryResult msg = _player->CanUnequipItem(src, !_player->IsBagPos (src));
        if (msg != EQUIP_ERR_OK)
        {
            _player->SendEquipError(msg, pItem, nullptr);
            return;
        }
    }

    ItemPosCountVec dest;
    InventoryResult msg = _player->CanStoreItem(dstbag, NULL_SLOT, dest, pItem, false);
    if (msg != EQUIP_ERR_OK)
    {
        _player->SendEquipError(msg, pItem, nullptr);
        return;
    }

    // no-op: placed in same slot
    if (dest.size() == 1 && dest[0].pos == src)
    {
        // just remove grey item state
        _player->SendEquipError(EQUIP_ERR_NONE, pItem, nullptr);
        return;
    }

    _player->RemoveItem(srcbag, srcslot, true);
    _player->StoreItem(dest, pItem, true);
}

/**
 * @brief 处理设置弹药网络包（CMSG_SET_AMMO）
 *
 * @details 当玩家设置自动射击/投掷使用的弹药时调用此函数。
 *          弓/弩使用箭矢，枪械使用子弹，投掷武器使用投掷物品。
 *          设置后系统会在使用相关武器时自动消耗弹药。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - item: 弹药物品模板ID（0表示取消弹药设置）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 检查玩家是否存活
 *       2. 解析网络包获取弹药ID
 *       3. 如果弹药ID不为0：
 *          - 验证玩家是否拥有该弹药
 *          - 调用 Player::SetAmmo() 设置弹药
 *       4. 如果弹药ID为0，调用 Player::RemoveAmmo() 移除弹药设置
 */
void WorldSession::HandleSetAmmoOpcode(WorldPacket& recvData)
{
    if (!_player->IsAlive())
    {
        _player->SendEquipError(EQUIP_ERR_YOU_ARE_DEAD, nullptr, nullptr);
        return;
    }

    TC_LOG_DEBUG("network", "WORLD: CMSG_SET_AMMO");
    uint32 item;

    recvData >> item;

    if (item)
    {
        if (!_player->GetItemCount(item))
        {
            _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
            return;
        }

        _player->SetAmmo(item);
    }
    else
        _player->RemoveAmmo();
}

/**
 * @brief 发送附魔日志给客户端
 *
 * @details 当物品附魔成功时，向周围玩家发送附魔效果日志。
 *          其他玩家可以看到附魔的光效和音效。
 *
 * @param target 目标物品拥有者的GUID
 * @param caster 施法者（附魔者）的GUID
 * @param itemId 物品模板ID
 * @param enchantId 附魔效果ID
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 构建附魔日志数据包（SMSG_ENCHANTMENTLOG）
 *       2. 填充目标、施法者、物品ID、附魔ID
 *       3. 向周围玩家广播数据包
 */
void WorldSession::SendEnchantmentLog(ObjectGuid target, ObjectGuid caster, uint32 itemId, uint32 enchantId)
{
    WorldPacket data(SMSG_ENCHANTMENTLOG, (8+8+4+4));     // last check 2.0.10
    data << target.WriteAsPacked();
    data << caster.WriteAsPacked();
    data << uint32(itemId);
    data << uint32(enchantId);
    GetPlayer()->SendMessageToSet(&data, true);
}

/**
 * @brief 发送物品附魔时间更新给客户端
 *
 * @details 当临时附魔的剩余时间发生变化时，通知客户端更新显示。
 *          例如：磨刀石、武器油等临时附魔的持续时间。
 *
 * @param Playerguid 玩家的GUID
 * @param Itemguid 物品的GUID
 * @param slot 附魔槽位编号
 * @param Duration 剩余持续时间（毫秒）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 构建附魔时间更新数据包（SMSG_ITEM_ENCHANT_TIME_UPDATE）
 *       2. 填充物品GUID、槽位、持续时间、玩家GUID
 *       3. 发送数据包给客户端
 */
void WorldSession::SendItemEnchantTimeUpdate(ObjectGuid Playerguid, ObjectGuid Itemguid, uint32 slot, uint32 Duration)
{
                                                            // last check 2.0.10
    WorldPacket data(SMSG_ITEM_ENCHANT_TIME_UPDATE, (8+4+4+8));
    data << uint64(Itemguid);
    data << uint32(slot);
    data << uint32(Duration);
    data << uint64(Playerguid);
    SendPacket(&data);
}

/**
 * @brief 处理物品套装名称查询网络包（CMSG_ITEM_NAME_QUERY）
 *
 * @details 当客户端需要获取套装物品的名称信息时调用此函数。
 *          套装名称用于显示套装奖励信息。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - itemid: 套装ID
 *        - guid: 物品GUID（未使用）
 *
 * @return 无返回值（通过发送响应包返回数据）
 *
 * @note 主要流程：
 *       1. 解析网络包获取套装ID
 *       2. 查找套装名称数据
 *       3. 根据玩家语言获取本地化名称
 *       4. 构建并发送响应数据包，包含套装ID、名称、装备类型
 */
void WorldSession::HandleItemNameQueryOpcode(WorldPacket& recvData)
{
    uint32 itemid;
    recvData >> itemid;
    recvData.read_skip<uint64>();                          // guid

    TC_LOG_DEBUG("network", "WORLD: CMSG_ITEM_NAME_QUERY {}", itemid);
    ItemSetNameEntry const* pName = sObjectMgr->GetItemSetNameEntry(itemid);
    if (pName)
    {
        std::string Name = pName->name;
        LocaleConstant localeConstant = GetSessionDbLocaleIndex();
        if (localeConstant != LOCALE_enUS)
            if (ItemSetNameLocale const* isnl = sObjectMgr->GetItemSetNameLocale(itemid))
                ObjectMgr::GetLocaleString(isnl->Name, localeConstant, Name);

        WorldPacket data(SMSG_ITEM_NAME_QUERY_RESPONSE, (4+Name.size()+1+4));
        data << uint32(itemid);
        data << Name;
        data << uint32(pName->InventoryType);
        SendPacket(&data);
    }
}

/**
 * @brief 处理包装物品网络包（CMSG_WRAP_ITEM）
 *
 * @details 当玩家使用包装纸（如蓝色包装纸、红色包装纸等）包装物品时调用此函数。
 *          包装后的物品变成礼物，可以交易给其他玩家，对方打开后会获得原物品。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - gift_bag: 包装纸所在背包编号
 *        - gift_slot: 包装纸所在槽位编号
 *        - item_bag: 要包装物品所在背包编号
 *        - item_slot: 要包装物品所在槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取包装纸和物品位置
 *       2. 验证包装纸是否存在且为有效包装物品
 *       3. 验证被包装物品是否存在且符合包装条件：
 *          - 不能是包装纸自己
 *          - 不能是已装备的物品
 *          - 不能是已包装的物品
 *          - 不能是背包
 *          - 不能是灵魂绑定的物品
 *          - 不能是可堆叠的物品
 *          - 不能是有限数量的物品
 *       4. 在数据库中创建礼物记录
 *       5. 修改物品为包装后的形态
 *       6. 销毁包装纸
 */
void WorldSession::HandleWrapItemOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "Received opcode CMSG_WRAP_ITEM");

    uint8 gift_bag, gift_slot, item_bag, item_slot;

    recvData >> gift_bag >> gift_slot;                     // paper
    recvData >> item_bag >> item_slot;                     // item

    TC_LOG_DEBUG("network", "WRAP: receive gift_bag = {}, gift_slot = {}, item_bag = {}, item_slot = {}", gift_bag, gift_slot, item_bag, item_slot);

    Item* gift = _player->GetItemByPos(gift_bag, gift_slot);
    if (!gift)
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, gift, nullptr);
        return;
    }

    if (!gift->GetTemplate()->HasFlag(ITEM_FLAG_IS_WRAPPER)) // cheating: non-wrapper wrapper
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, gift, nullptr);
        return;
    }

    Item* item = _player->GetItemByPos(item_bag, item_slot);

    if (!item)
    {
        _player->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, item, nullptr);
        return;
    }

    if (item == gift)                                          // not possable with pacjket from real client
    {
        _player->SendEquipError(EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    if (item->IsEquipped())
    {
        _player->SendEquipError(EQUIP_ERR_EQUIPPED_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    if (!item->GetGuidValue(ITEM_FIELD_GIFTCREATOR).IsEmpty())      // HasFlag(ITEM_FIELD_FLAGS, ITEM_FLAGS_WRAPPED);
    {
        _player->SendEquipError(EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    if (item->IsBag())
    {
        _player->SendEquipError(EQUIP_ERR_BAGS_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    if (item->IsSoulBound())
    {
        _player->SendEquipError(EQUIP_ERR_BOUND_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    if (item->GetMaxStackCount() != 1)
    {
        _player->SendEquipError(EQUIP_ERR_STACKABLE_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    // maybe not correct check  (it is better than nothing)
    if (item->GetTemplate()->MaxCount>0)
    {
        _player->SendEquipError(EQUIP_ERR_UNIQUE_CANT_BE_WRAPPED, item, nullptr);
        return;
    }

    CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();

    CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_CHAR_GIFT);
    stmt->setUInt32(0, item->GetOwnerGUID().GetCounter());
    stmt->setUInt32(1, item->GetGUID().GetCounter());
    stmt->setUInt32(2, item->GetEntry());
    stmt->setUInt32(3, item->GetUInt32Value(ITEM_FIELD_FLAGS));
    trans->Append(stmt);

    item->SetEntry(gift->GetEntry());

    switch (item->GetEntry())
    {
        case 5042:  item->SetEntry(5043); break;
        case 5048:  item->SetEntry(5044); break;
        case 17303: item->SetEntry(17302); break;
        case 17304: item->SetEntry(17305); break;
        case 17307: item->SetEntry(17308); break;
        case 21830: item->SetEntry(21831); break;
    }
    item->SetGuidValue(ITEM_FIELD_GIFTCREATOR, _player->GetGUID());
    item->SetUInt32Value(ITEM_FIELD_FLAGS, ITEM_FIELD_FLAG_WRAPPED);
    item->SetState(ITEM_CHANGED, _player);

    if (item->GetState() == ITEM_NEW)                          // save new item, to have alway for `character_gifts` record in `item_instance`
    {
        // after save it will be impossible to remove the item from the queue
        RemoveItemFromUpdateQueueOf(item, _player);
        item->SaveToDB(trans);                                   // item gave inventory record unchanged and can be save standalone
    }
    CharacterDatabase.CommitTransaction(trans);

    uint32 count = 1;
    _player->DestroyItemCount(gift, count, true);
}

/**
 * @brief 处理镶嵌宝石网络包（CMSG_SOCKET_GEMS）
 *
 * @details 当玩家在装备上镶嵌宝石时调用此函数。
 *          宝石可以镶嵌到装备的插槽中，提供额外属性加成。
 *          支持多种颜色的宝石和插槽，以及多彩宝石的特殊要求。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - item_guid: 目标装备的GUID
 *        - gem_guids[]: 最多3个宝石的GUID数组（对应3个插槽）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取装备和宝石GUID
 *       2. 验证装备和宝石是否存在
 *       3. 检查是否尝试重复镶嵌同一个宝石（作弊检测）
 *       4. 验证宝石与插槽的匹配：
 *          - 检查插槽是否存在
 *          - 验证宝石颜色与插槽颜色匹配
 *          - 多彩宝石只能放入多彩插槽，反之亦然
 *       5. 检查唯一装备条件：
 *          - 同一物品中不能有重复的唯一宝石
 *          - 检查宝石数量限制
 *       6. 移除旧的宝石附魔
 *       7. 应用新的宝石附魔
 *       8. 检查并更新插槽奖励状态
 *       9. 更新多彩宝石激活状态
 *       10. 清除物品的可交易标记
 */
void WorldSession::HandleSocketOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: CMSG_SOCKET_GEMS");

    ObjectGuid item_guid;
    ObjectGuid gem_guids[MAX_GEM_SOCKETS];

    recvData >> item_guid;
    if (!item_guid)
        return;

    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)
        recvData >> gem_guids[i];

    //cheat -> tried to socket same gem multiple times
    if ((gem_guids[0] && (gem_guids[0] == gem_guids[1] || gem_guids[0] == gem_guids[2])) ||
        (gem_guids[1] && (gem_guids[1] == gem_guids[2])))
        return;

    Item* itemTarget = _player->GetItemByGuid(item_guid);
    if (!itemTarget)                                         //missing item to socket
        return;

    ItemTemplate const* itemProto = itemTarget->GetTemplate();
    if (!itemProto)
        return;

    //this slot is excepted when applying / removing meta gem bonus
    uint8 slot = itemTarget->IsEquipped() ? itemTarget->GetSlot() : uint8(NULL_SLOT);

    Item* Gems[MAX_GEM_SOCKETS];
    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)
        Gems[i] = gem_guids[i] ? _player->GetItemByGuid(gem_guids[i]) : nullptr;

    GemPropertiesEntry const* GemProps[MAX_GEM_SOCKETS];
    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)                //get geminfo from dbc storage
        GemProps[i] = (Gems[i]) ? sGemPropertiesStore.LookupEntry(Gems[i]->GetTemplate()->GemProperties) : nullptr;

    // Find first prismatic socket
    int32 firstPrismatic = 0;
    while (firstPrismatic < MAX_GEM_SOCKETS && itemProto->Socket[firstPrismatic].Color)
        ++firstPrismatic;

    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)                //check for hack maybe
    {
        if (!GemProps[i])
            continue;

        // tried to put gem in socket where no socket exists (take care about prismatic sockets)
        if (!itemProto->Socket[i].Color)
        {
            // no prismatic socket
            if (!itemTarget->GetEnchantmentId(PRISMATIC_ENCHANTMENT_SLOT))
                return;

            if (i != firstPrismatic)
                return;
        }

        // tried to put normal gem in meta socket
        if (itemProto->Socket[i].Color == SOCKET_COLOR_META && GemProps[i]->Type != SOCKET_COLOR_META)
            return;

        // tried to put meta gem in normal socket
        if (itemProto->Socket[i].Color != SOCKET_COLOR_META && GemProps[i]->Type == SOCKET_COLOR_META)
            return;
    }

    uint32 GemEnchants[MAX_GEM_SOCKETS];
    uint32 OldEnchants[MAX_GEM_SOCKETS];
    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)                //get new and old enchantments
    {
        GemEnchants[i] = (GemProps[i]) ? GemProps[i]->EnchantID : 0;
        OldEnchants[i] = itemTarget->GetEnchantmentId(EnchantmentSlot(SOCK_ENCHANTMENT_SLOT+i));
    }

    // check unique-equipped conditions
    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)
    {
        if (!Gems[i])
            continue;

        // continue check for case when attempt add 2 similar unique equipped gems in one item.
        ItemTemplate const* iGemProto = Gems[i]->GetTemplate();

        // unique item (for new and already placed bit removed enchantments
        if (iGemProto->HasFlag(ITEM_FLAG_UNIQUE_EQUIPPABLE))
        {
            for (int j = 0; j < MAX_GEM_SOCKETS; ++j)
            {
                if (i == j)                                    // skip self
                    continue;

                if (Gems[j])
                {
                    if (iGemProto->ItemId == Gems[j]->GetEntry())
                    {
                        _player->SendEquipError(EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED, itemTarget, nullptr);
                        return;
                    }
                }
                else if (OldEnchants[j])
                {
                    if (SpellItemEnchantmentEntry const* enchantEntry = sSpellItemEnchantmentStore.LookupEntry(OldEnchants[j]))
                    {
                        if (iGemProto->ItemId == enchantEntry->SrcItemID)
                        {
                            _player->SendEquipError(EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED, itemTarget, nullptr);
                            return;
                        }
                    }
                }
            }
        }

        // unique limit type item
        int32 limit_newcount = 0;
        if (iGemProto->ItemLimitCategory)
        {
            if (ItemLimitCategoryEntry const* limitEntry = sItemLimitCategoryStore.LookupEntry(iGemProto->ItemLimitCategory))
            {
                // NOTE: limitEntry->Flags is not checked because if item has limit then it is applied in equip case
                for (int j = 0; j < MAX_GEM_SOCKETS; ++j)
                {
                    if (Gems[j])
                    {
                        // new gem
                        if (iGemProto->ItemLimitCategory == Gems[j]->GetTemplate()->ItemLimitCategory)
                            ++limit_newcount;
                    }
                    else if (OldEnchants[j])
                    {
                        // existing gem
                        if (SpellItemEnchantmentEntry const* enchantEntry = sSpellItemEnchantmentStore.LookupEntry(OldEnchants[j]))
                            if (ItemTemplate const* jProto = sObjectMgr->GetItemTemplate(enchantEntry->SrcItemID))
                                if (iGemProto->ItemLimitCategory == jProto->ItemLimitCategory)
                                    ++limit_newcount;
                    }
                }

                if (limit_newcount > 0 && uint32(limit_newcount) > limitEntry->Quantity)
                {
                    _player->SendEquipError(EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED, itemTarget, nullptr);
                    return;
                }
            }
        }

        // for equipped item check all equipment for duplicate equipped gems
        if (itemTarget->IsEquipped())
        {
            if (InventoryResult res = _player->CanEquipUniqueItem(Gems[i], slot, std::max(limit_newcount, 0)))
            {
                _player->SendEquipError(res, itemTarget, nullptr);
                return;
            }
        }
    }

    bool SocketBonusActivated = itemTarget->GemsFitSockets();    //save state of socketbonus
    _player->ToggleMetaGemsActive(slot, false);             //turn off all metagems (except for the target item)

    //if a meta gem is being equipped, all information has to be written to the item before testing if the conditions for the gem are met

    //remove ALL enchants
    for (uint32 enchant_slot = SOCK_ENCHANTMENT_SLOT; enchant_slot < SOCK_ENCHANTMENT_SLOT + MAX_GEM_SOCKETS; ++enchant_slot)
        _player->ApplyEnchantment(itemTarget, EnchantmentSlot(enchant_slot), false);

    for (int i = 0; i < MAX_GEM_SOCKETS; ++i)
    {
        if (GemEnchants[i])
        {
            itemTarget->SetEnchantment(EnchantmentSlot(SOCK_ENCHANTMENT_SLOT+i), GemEnchants[i], 0, 0, _player->GetGUID());
            if (Item* guidItem = _player->GetItemByGuid(gem_guids[i]))
                _player->DestroyItem(guidItem->GetBagSlot(), guidItem->GetSlot(), true);
        }
    }

    for (uint32 enchant_slot = SOCK_ENCHANTMENT_SLOT; enchant_slot < SOCK_ENCHANTMENT_SLOT+MAX_GEM_SOCKETS; ++enchant_slot)
        _player->ApplyEnchantment(itemTarget, EnchantmentSlot(enchant_slot), true);

    bool SocketBonusToBeActivated = itemTarget->GemsFitSockets();//current socketbonus state
    if (SocketBonusActivated ^ SocketBonusToBeActivated)     //if there was a change...
    {
        _player->ApplyEnchantment(itemTarget, BONUS_ENCHANTMENT_SLOT, false);
        itemTarget->SetEnchantment(BONUS_ENCHANTMENT_SLOT, (SocketBonusToBeActivated ? itemTarget->GetTemplate()->socketBonus : 0), 0, 0, _player->GetGUID());
        _player->ApplyEnchantment(itemTarget, BONUS_ENCHANTMENT_SLOT, true);
        //it is not displayed, client has an inbuilt system to determine if the bonus is activated
    }

    _player->ToggleMetaGemsActive(slot, true);              //turn on all metagems (except for target item)

    _player->RemoveTradeableItem(itemTarget);
    itemTarget->ClearSoulboundTradeable(_player);           // clear tradeable flag

    itemTarget->SendUpdateSockets();
}

/**
 * @brief 处理取消临时附魔网络包（CMSG_CANCEL_TEMP_ENCHANTMENT）
 *
 * @details 当玩家想要移除武器上的临时附魔时调用此函数。
 *          临时附魔如磨刀石、武器油等，可以通过右键点击取消。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - eslot: 装备槽位编号
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取装备槽位
 *       2. 验证槽位是否为装备槽位
 *       3. 获取槽位中的物品
 *       4. 检查物品是否有临时附魔
 *       5. 移除临时附魔效果
 *       6. 清除附魔数据
 */
void WorldSession::HandleCancelTempEnchantmentOpcode(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: CMSG_CANCEL_TEMP_ENCHANTMENT");

    uint32 eslot;

    recvData >> eslot;

    // apply only to equipped item
    if (!Player::IsEquipmentPos(INVENTORY_SLOT_BAG_0, eslot))
        return;

    Item* item = GetPlayer()->GetItemByPos(INVENTORY_SLOT_BAG_0, eslot);

    if (!item)
        return;

    if (!item->GetEnchantmentId(TEMP_ENCHANTMENT_SLOT))
        return;

    GetPlayer()->ApplyEnchantment(item, TEMP_ENCHANTMENT_SLOT, false);
    item->ClearEnchantment(TEMP_ENCHANTMENT_SLOT);
}

/**
 * @brief 处理物品退款信息请求网络包（CMSG_ITEM_REFUND_INFO）
 *
 * @details 当玩家查看可退款物品的退款信息时调用此函数。
 *          某些物品在购买后一定时间内可以退款，需要显示退款详情。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - guid: 物品的唯一标识符（GUID）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品GUID
 *       2. 根据GUID查找物品
 *       3. 如果物品存在，发送退款信息给客户端
 */
void WorldSession::HandleItemRefundInfoRequest(WorldPacket& recvData)
{
    TC_LOG_DEBUG("network", "WORLD: CMSG_ITEM_REFUND_INFO");

    ObjectGuid guid;
    recvData >> guid;                                      // item guid

    Item* item = _player->GetItemByGuid(guid);
    if (!item)
    {
        TC_LOG_DEBUG("network", "Item refund: item not found!");
        return;
    }

    GetPlayer()->SendRefundInfo(item);
}

/**
 * @brief 处理物品退款网络包（CMSG_ITEM_REFUND）
 *
 * @details 当玩家确认退款物品时调用此函数。
 *          物品会被移除，玩家获得原购买价格的货币和货币代币。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - guid: 物品的唯一标识符（GUID）
 *
 * @return 无返回值
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品GUID
 *       2. 根据GUID查找物品
 *       3. 验证物品是否正在被分解（防止重复操作）
 *       4. 调用 Player::RefundItem() 执行退款操作
 */
void WorldSession::HandleItemRefund(WorldPacket &recvData)
{
    TC_LOG_DEBUG("network", "WORLD: CMSG_ITEM_REFUND");
    ObjectGuid guid;
    recvData >> guid;                                      // item guid

    Item* item = _player->GetItemByGuid(guid);
    if (!item)
    {
        TC_LOG_DEBUG("network", "Item refund: item not found!");
        return;
    }

    // Don't try to refund item currently being disenchanted
    if (_player->GetLootGUID() == guid)
        return;

    GetPlayer()->RefundItem(item);
}

/**
 * @brief 处理物品文本查询网络包（CMSG_ITEM_TEXT_QUERY）
 *
 * @details 当客户端请求物品的文本内容时调用此函数。
 *          例如：礼物包装的物品可能包含发送者的留言文本。
 *          当玩家点击带有文本标记的物品时会触发此请求。
 *
 * @param recvData 接收到的网络包数据，包含以下字段：
 *        - itemGuid: 物品的唯一标识符（GUID）
 *
 * @return 无返回值（通过发送响应包返回数据）
 *
 * @note 主要流程：
 *       1. 解析网络包获取物品GUID
 *       2. 根据GUID查找物品
 *       3. 如果找到物品：
 *          - 发送成功响应（has text = 0）
 *          - 包含物品GUID和文本内容
 *       4. 如果未找到物品：
 *          - 发送失败响应（has text = 1，表示无文本）
 */
void WorldSession::HandleItemTextQuery(WorldPacket& recvData )
{
    ObjectGuid itemGuid;
    recvData >> itemGuid;

    TC_LOG_DEBUG("network", "CMSG_ITEM_TEXT_QUERY {}", itemGuid.ToString());

    WorldPacket data(SMSG_ITEM_TEXT_QUERY_RESPONSE, (4+10));    // guess size

    if (Item* item = _player->GetItemByGuid(itemGuid))
    {
        data << uint8(0);                                       // has text
        data << uint64(itemGuid);                               // item guid
        data << item->GetText();
    }
    else
    {
        data << uint8(1);                                       // no text
    }

    SendPacket(&data);
}
